// Copyright (c) 2024 - 2025 : FRC 2106 : The Junkyard Dogs
// https://www.team2106.org

// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file at
// the root directory of this project.

package frc.robot.subsystems.elevator;

import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.SignalLogger;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.subsystems.superstructure.SuperstructureState;
import java.util.function.DoubleSupplier;
import org.littletonrobotics.junction.Logger;

/**
 * Elevator subsystem that binds IO to higher-level commands, logging, and SysId routines.
 * Periodically updates targets from superstructure state, publishes telemetry via AdvantageKit, and
 * exposes standard SysId tests for characterization and tuning workflows.
 *
 * <p>Conversion factor note: METERS_PER_MOTOR_ROTATION is the linear travel per motor rotation
 * derived from gearing and spool/chain geometry, which is used to translate between mechanism space
 * (meters) and motor space (rotations).
 */
public class SUB_Elevator extends SubsystemBase {
	/** Hardware abstraction for elevator (real or sim). */
	private final IO_ElevatorBase io;

	/** Telemetry container populated every loop for logging and dashboards. */
	private final IO_ElevatorBase.ElevatorInputs inputs = new IO_ElevatorBase.ElevatorInputs();

	/** Current superstructure state driving elevator targets. */
	private SuperstructureState.State localState = SuperstructureState.IDLE;

	/** SysId routine wrapper for quasistatic and dynamic tests. */
	private final SysIdRoutine sysIdRoutine;

	/**
	 * Constructs the elevator subsystem with the specified IO layer and initializes SysId. SysId is
	 * configured with a moderate dynamic step voltage and default ramp rate and timeout, logging
	 * state transitions to the Phoenix 6 SignalLogger for later analysis.
	 *
	 * @param io elevator IO implementation (real or simulation)
	 */
	public SUB_Elevator(IO_ElevatorBase io) {
		this.io = io;

		// Configure Phoenix 6 logger output path (optional: empty string uses default).
		SignalLogger.setPath("");

		// Configure SysId routine: default ramp rate, 4V dynamic step, default timeout.
		// The state callback is written into the vendor logger, which can be post-processed for
		// fitting.
		sysIdRoutine =
				new SysIdRoutine(
						new SysIdRoutine.Config(
								null, // Default ramp rate (1 V/s)
								Volts.of(4), // Reduced dynamic step voltage to 4 V
								null, // Default timeout (10 s)
								(state) -> SignalLogger.writeString("state", state.toString())),
						new SysIdRoutine.Mechanism((volts) -> io.setVoltage(volts.in(Volts)), null, this));
	}

	/**
	 * Runs once per scheduler loop to command setpoints, refresh inputs, and emit logs. Elevator
	 * target height is driven by the current superstructure state and logged via AdvantageKit.
	 */
	@Override
	public void periodic() {
		io.setPositionM(localState.getHeightM());
		io.updateInputs(inputs);
		Logger.processInputs("Elevator", inputs);
	}

	/**
	 * Direct voltage helper for commands/tests that bypass closed-loop control.
	 *
	 * @param volts command in volts applied symmetrically to the mechanism
	 */
	public void setVoltage(double volts) {
		io.setVoltage(volts);
	}

	/**
	 * Wraps a provided SysId command in a simple sequence for composition in autonomous or testing.
	 *
	 * @param sysIdCommand command generated by the routine’s factories
	 * @return the composed command
	 */
	public Command createSysIdCommand(Command sysIdCommand) {
		return Commands.sequence(sysIdCommand);
	}

	/**
	 * Factory for quasistatic SysId test using the configured routine.
	 *
	 * @param direction forward or reverse
	 * @return generated command for the test
	 */
	public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
		return sysIdRoutine.quasistatic(direction);
	}

	/**
	 * Factory for dynamic SysId test using the configured routine.
	 *
	 * @param direction forward or reverse
	 * @return generated command for the test
	 */
	public Command sysIdDynamic(SysIdRoutine.Direction direction) {
		return sysIdRoutine.dynamic(direction);
	}

	/**
	 * Updates the local superstructure-driven state which defines target elevator height.
	 *
	 * @param newLocalState the desired state
	 */
	public void updateLocalState(SuperstructureState.State newLocalState) {
		localState = newLocalState;
	}

	/**
	 * Returns the currently active superstructure state for the elevator.
	 *
	 * @return the current state
	 */
	public SuperstructureState.State getCurrentLocalState() {
		return localState;
	}

	/**
	 * Returns a DoubleSupplier view of the current height in meters for dashboards or constraints.
	 *
	 * @return supplier yielding current elevator height (m)
	 */
	public DoubleSupplier getHeight() {
		return () -> inputs.heightM;
	}
}
